# Generated by Django 5.1.4 on 2025-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_recommendedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedplace',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
