# Generated by Django 5.1.4 on 2025-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_recommendedplace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedplace',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='recommendedplace',
            name='hotel_rating',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendedplace',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
