# Generated by Django 5.1.4 on 2025-03-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_recommendedplace_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedplace',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recommendedplace',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
