# Generated by Django 5.1.4 on 2025-04-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_alter_restaurant_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image_url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='Unknown', max_length=200, upload_to=''),
        ),
    ]
