# Generated by Django 5.1.4 on 2025-04-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_remove_restaurant_image_url_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to='restaurants/'),
        ),
    ]
