# Generated by Django 5.2 on 2025-04-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0015_remove_hotel_image_url_hotel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('type', models.CharField(choices=[('street', 'Гудамжны зогсоол'), ('lot', 'Зогсоолын талбай'), ('underground', 'Газрын доорхи'), ('private', 'Хувийн зогсоол')], max_length=20, verbose_name='Төрөл')),
                ('capacity', models.PositiveIntegerField(verbose_name='Багтаамж')),
                ('price', models.CharField(max_length=100, verbose_name='Үнэ')),
                ('distance', models.CharField(max_length=50, verbose_name='Зай')),
                ('is_covered', models.BooleanField(default=False, verbose_name='Дээвэртэй эсэх')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='backend_app.place')),
            ],
        ),
    ]
