# Generated by Django 5.2 on 2025-04-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='backend_app.recommendedplace'),
        ),
    ]
